// SPDX-License-Identifier: LGPL-2.1-or-later

/***************************************************************************
 *   Copyright (c) 2007 Jürgen Riegel <juergen.riegel@web.de>              *
 *                                                                         *
 *   This file is part of the FreeCAD CAx development system.              *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Library General Public           *
 *   License as published by the Free Software Foundation; either          *
 *   version 2 of the License, or (at your option) any later version.      *
 *                                                                         *
 *   This library  is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Library General Public License for more details.                  *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this library; see the file COPYING.LIB. If not,    *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,         *
 *   Suite 330, Boston, MA  02111-1307, USA                                *
 *                                                                         *
 ***************************************************************************/

#include <Base/FileInfo.h>
#include <Base/Interpreter.h>
#include <Base/Stream.h>

#include <cstring>
#include <map>
#include <memory>
#include <utility>
#include <vector>

#include "Document.h"
#include "DocumentCollaborationService.h"
#include "DocumentObject.h"
#include "DocumentObjectPy.h"
#include "DocumentSettings.h"
#include "DocumentSettingsPy.h"
#include "MergeDocuments.h"
#include "RecomputeHandlePy.h"

// inclusion of the generated files (generated By DocumentPy.xml)
#include "DocumentPy.h"
#include "DocumentPy.cpp"
#include <boost/regex.hpp>
#include <Base/PyWrapParseTupleAndKeywords.h>

using namespace App;

namespace
{

const char* saveDispositionName(const DocumentSaveDisposition disposition)
{
    switch (disposition) {
        case DocumentSaveDisposition::Written:
            return "written";
        case DocumentSaveDisposition::Unchanged:
            return "unchanged";
        case DocumentSaveDisposition::CopyWritten:
            return "copy_written";
        case DocumentSaveDisposition::Failed:
            return "failed";
    }
    return "failed";
}

const char* fileStateName(const DocumentFileState state)
{
    switch (state) {
        case DocumentFileState::NotSaved:
            return "not_saved";
        case DocumentFileState::Clean:
            return "clean";
        case DocumentFileState::Modified:
            return "modified";
    }
    return "modified";
}

const char* saveIntentName(const DocumentSaveIntent intent)
{
    switch (intent) {
        case DocumentSaveIntent::Canonical:
            return "canonical";
        case DocumentSaveIntent::Force:
            return "force";
        case DocumentSaveIntent::SaveAs:
            return "save_as";
        case DocumentSaveIntent::Copy:
            return "copy";
        case DocumentSaveIntent::Recovery:
            return "recovery";
    }
    return "canonical";
}

Py::Dict saveOutcomeToPy(const DocumentSaveOutcome& outcome)
{
    Py::Dict result;
    result["success"] = Py::Boolean(outcome.succeeded());
    result["intent"] = Py::String(saveIntentName(outcome.intent));
    result["save_disposition"] = Py::String(saveDispositionName(outcome.disposition));
    result["file_written"] = Py::Boolean(outcome.fileWritten);
    result["durability_verified"] = Py::Boolean(outcome.durabilityVerified);
    result["unchanged"] = Py::Boolean(
        outcome.disposition == DocumentSaveDisposition::Unchanged);
    result["canonical_path"] = Py::String(outcome.canonicalPath);
    result["target_path"] = Py::String(outcome.targetPath);
    result["resulting_state"] = Py::String(fileStateName(outcome.resultingState));
    result["resulting_clean"] = Py::Boolean(
        outcome.resultingState == DocumentFileState::Clean
        && !outcome.lastCanonicalSaveFailed);
    result["last_canonical_save_failed"] = Py::Boolean(outcome.lastCanonicalSaveFailed);
    result["error_code"] = Py::String(outcome.errorCode);
    result["message"] = Py::String(outcome.message);
    Py::List pending;
    if (outcome.pendingChanges.testFlag(DocumentFileChange::Model)) {
        pending.append(Py::String("model"));
    }
    if (outcome.pendingChanges.testFlag(DocumentFileChange::Appearance)) {
        pending.append(Py::String("appearance"));
    }
    result["pending_changes"] = pending;
    Py::List warnings;
    for (const auto& warning : outcome.warnings) {
        warnings.append(Py::String(warning));
    }
    result["warnings"] = warnings;
    return result;
}

constexpr const char* PreparedEditCapsuleName = "App.PreparedEdit";

class PythonCompatibilityCallbackFailure final
{};

class PythonCompatibilityCallbackError final
{
public:
    ~PythonCompatibilityCallbackError()
    {
        if ((!_type && !_value && !_traceback) || !Py_IsInitialized()) {
            return;
        }
        Base::PyGILStateLocker gil;
        Py_XDECREF(_type);
        Py_XDECREF(_value);
        Py_XDECREF(_traceback);
    }

    void capture()
    {
        PyErr_Fetch(&_type, &_value, &_traceback);
        if (_type) {
            return;
        }
        PyErr_SetString(PyExc_RuntimeError,
                        "compatibility callback failed without a Python exception");
        PyErr_Fetch(&_type, &_value, &_traceback);
    }

    void restore()
    {
        // Cleanup performed by the native coordinator is allowed to execute
        // Python-backed objects.  Never let a secondary cleanup error replace
        // the callback/postcondition exception promised by this API.
        PyErr_Clear();
        PyErr_Restore(std::exchange(_type, nullptr),
                      std::exchange(_value, nullptr),
                      std::exchange(_traceback, nullptr));
    }

    [[nodiscard]] bool captured() const noexcept
    {
        return _type || _value || _traceback;
    }

private:
    PyObject* _type {nullptr};
    PyObject* _value {nullptr};
    PyObject* _traceback {nullptr};
};

const char* documentLifecycleStateName(DocumentLifecycleState state)
{
    switch (state) {
        case DocumentLifecycleState::Live:
            return "Live";
        case DocumentLifecycleState::Closing:
            return "Closing";
        case DocumentLifecycleState::Closed:
            return "Closed";
    }
    return "Closed";
}

const char* revisionKindName(DocumentRevisionKind kind)
{
    switch (kind) {
        case DocumentRevisionKind::ObjectExistence:
            return "ObjectExistence";
        case DocumentRevisionKind::ObjectModel:
            return "ObjectModel";
        case DocumentRevisionKind::ObjectStructure:
            return "ObjectStructure";
        case DocumentRevisionKind::DocumentStructure:
            return "DocumentStructure";
        case DocumentRevisionKind::UnknownModelMutation:
            return "UnknownModelMutation";
        case DocumentRevisionKind::ObjectProperty:
            return "ObjectProperty";
    }
    return "Invalid";
}

DocumentRevisionKey revisionKeyFromPython(PyObject* object)
{
    if (!PyDict_Check(object)) {
        throw Py::TypeError(
            "each revision key must be a dict with 'kind', optional 'subject', and optional 'property_name'");
    }
    PyObject* kindObject = PyDict_GetItemString(object, "kind");
    PyObject* subjectObject = PyDict_GetItemString(object, "subject");
    PyObject* propertyNameObject = PyDict_GetItemString(object, "property_name");
    if (!kindObject || !PyUnicode_Check(kindObject)) {
        throw Py::TypeError("revision key 'kind' must be a string");
    }
    if (subjectObject && !PyUnicode_Check(subjectObject)) {
        throw Py::TypeError("revision key 'subject' must be a string");
    }
    if (propertyNameObject && !PyUnicode_Check(propertyNameObject)) {
        throw Py::TypeError("revision key 'property_name' must be a string");
    }
    const char* kind = PyUnicode_AsUTF8(kindObject);
    const char* subject = subjectObject ? PyUnicode_AsUTF8(subjectObject) : "";
    const char* propertyName =
        propertyNameObject ? PyUnicode_AsUTF8(propertyNameObject) : "";
    if (!kind || !subject || !propertyName) {
        throw Py::Exception();
    }
    if (std::strcmp(kind, "ObjectProperty") == 0) {
        return DocumentRevisionKey::objectProperty(subject, propertyName);
    }
    if (*propertyName != '\0') {
        throw Py::ValueError("property_name is only valid for ObjectProperty revision keys");
    }
    if (std::strcmp(kind, "ObjectExistence") == 0) {
        return DocumentRevisionKey::objectExistence(subject);
    }
    if (std::strcmp(kind, "ObjectModel") == 0) {
        return DocumentRevisionKey::objectModel(subject);
    }
    if (std::strcmp(kind, "ObjectStructure") == 0) {
        return DocumentRevisionKey::objectStructure(subject);
    }
    if (std::strcmp(kind, "DocumentStructure") == 0 && *subject == '\0') {
        return DocumentRevisionKey::documentStructure();
    }
    if (std::strcmp(kind, "UnknownModelMutation") == 0 && *subject == '\0') {
        return DocumentRevisionKey::unknownModelMutation();
    }
    throw Py::ValueError("unknown or invalid document revision key kind/subject/property_name");
}

std::vector<DocumentRevisionKey> revisionKeysFromPython(PyObject* object)
{
    PyObject* fast = PySequence_Fast(object, "revision_keys must be a sequence of dicts");
    if (!fast) {
        throw Py::Exception();
    }
    std::vector<DocumentRevisionKey> keys;
    try {
        const auto count = PySequence_Fast_GET_SIZE(fast);
        keys.reserve(static_cast<std::size_t>(count));
        PyObject** items = PySequence_Fast_ITEMS(fast);
        for (Py_ssize_t index = 0; index < count; ++index) {
            keys.push_back(revisionKeyFromPython(items[index]));
        }
    }
    catch (...) {
        Py_DECREF(fast);
        throw;
    }
    Py_DECREF(fast);
    return keys;
}

std::vector<DocumentRevisionObservation> revisionObservationsFromPython(PyObject* object)
{
    PyObject* fast =
        PySequence_Fast(object, "expected_revisions must be a sequence of revision dicts");
    if (!fast) {
        throw Py::Exception();
    }
    std::vector<DocumentRevisionObservation> observations;
    try {
        const auto count = PySequence_Fast_GET_SIZE(fast);
        observations.reserve(static_cast<std::size_t>(count));
        PyObject** items = PySequence_Fast_ITEMS(fast);
        for (Py_ssize_t index = 0; index < count; ++index) {
            PyObject* item = items[index];
            if (!PyDict_Check(item)) {
                throw Py::TypeError("each expected revision must be a dict");
            }
            PyObject* revisionObject = PyDict_GetItemString(item, "revision");
            if (!revisionObject || !PyLong_Check(revisionObject)) {
                throw Py::TypeError("each expected revision must include an integer 'revision'");
            }
            const auto revision = static_cast<DocumentRevision>(PyLong_AsLong(revisionObject));
            if (PyErr_Occurred()) {
                throw Py::Exception();
            }
            observations.emplace_back(revisionKeyFromPython(item), revision);
        }
    }
    catch (...) {
        Py_DECREF(fast);
        throw;
    }
    Py_DECREF(fast);
    return observations;
}

std::map<std::string, std::string> stringMapFromPython(PyObject* object)
{
    if (!PyDict_Check(object)) {
        throw Py::TypeError("operation arguments must be a dict[str, str]");
    }
    std::map<std::string, std::string> result;
    PyObject* key = nullptr;
    PyObject* value = nullptr;
    Py_ssize_t position = 0;
    while (PyDict_Next(object, &position, &key, &value)) {
        if (!PyUnicode_Check(key) || !PyUnicode_Check(value)) {
            throw Py::TypeError("operation arguments must be a dict[str, str]");
        }
        const char* keyText = PyUnicode_AsUTF8(key);
        const char* valueText = PyUnicode_AsUTF8(value);
        if (!keyText || !valueText) {
            throw Py::Exception();
        }
        result.emplace(keyText, valueText);
    }
    return result;
}

Py::Dict revisionObservationToPython(const DocumentRevisionObservation& observation)
{
    Py::Dict result;
    result["kind"] = Py::String(revisionKindName(observation.key.kind));
    result["subject"] = Py::String(observation.key.subject);
    if (observation.key.kind == DocumentRevisionKind::ObjectProperty) {
        result["property_name"] = Py::String(observation.key.propertyName);
    }
    result["revision"] = Py::Long(observation.revision);
    return result;
}

Py::Dict editSessionToPython(const EditSession& session)
{
    Py::Dict result;
    result["session_id"] = Py::String(session.sessionId());
    result["actor_id"] = Py::String(session.actorId());
    result["document_instance_id"] = Py::Long(session.documentInstanceId());
    result["status"] = Py::String(session.status() == EditSessionStatus::Active ? "Active"
                                                                              : "Cancelled");
    if (session.cancellationReason()) {
        result["cancellation_reason"] = Py::String(*session.cancellationReason());
    }
    else {
        result["cancellation_reason"] = Py::None();
    }
    return result;
}

Py::Dict commitResultToPython(const DocumentCommitResult& commit)
{
    Py::Dict result;
    result["status"] = Py::String(documentCommitStatusName(commit.status));
    result["committed"] = Py::Boolean(commit.committed());
    result["operation_id"] = Py::String(commit.operationId);
    result["message"] = Py::String(commit.message);

    Py::List conflicts;
    for (const auto& conflict : commit.conflicts) {
        Py::Dict item;
        item["kind"] = Py::String(revisionKindName(conflict.key.kind));
        item["subject"] = Py::String(conflict.key.subject);
        if (conflict.key.kind == DocumentRevisionKind::ObjectProperty) {
            item["property_name"] = Py::String(conflict.key.propertyName);
        }
        item["expected"] = Py::Long(conflict.expected);
        item["current"] = Py::Long(conflict.current);
        conflicts.append(item);
    }
    result["conflicts"] = conflicts;

    Py::List published;
    for (const auto& observation : commit.publishedRevisions) {
        published.append(revisionObservationToPython(observation));
    }
    result["published_revisions"] = published;
    return result;
}

const char* preparedEditExecutionStatusName(PreparedEditExecutionStatus status)
{
    switch (status) {
        case PreparedEditExecutionStatus::Queued:
            return "Queued";
        case PreparedEditExecutionStatus::Running:
            return "Running";
        case PreparedEditExecutionStatus::Completed:
            return "Completed";
        case PreparedEditExecutionStatus::Cancelled:
            return "Cancelled";
        case PreparedEditExecutionStatus::Failed:
            return "Failed";
    }
    return "Invalid";
}

Py::Dict preparedEditExecutionSnapshotToPython(const PreparedEditExecutionSnapshot& snapshot)
{
    Py::Dict result;
    result["execution_id"] = Py::Long(snapshot.id);
    result["status"] = Py::String(preparedEditExecutionStatusName(snapshot.status));
    result["diagnostic"] = Py::String(snapshot.diagnostic);
    return result;
}

void preparedEditCapsuleDestructor(PyObject* capsule)
{
    auto* edit = static_cast<PreparedEdit*>(PyCapsule_GetPointer(capsule,
                                                                 PreparedEditCapsuleName));
    if (!edit) {
        PyErr_Clear();
        return;
    }
    delete edit;
}

PreparedEdit& preparedEditFromCapsule(PyObject* object)
{
    if (!PyCapsule_IsValid(object, PreparedEditCapsuleName)) {
        throw Py::TypeError("prepared_edit must be an App.PreparedEdit handle");
    }
    return *static_cast<PreparedEdit*>(PyCapsule_GetPointer(object, PreparedEditCapsuleName));
}

PyObject* preparedEditToCapsule(std::unique_ptr<PreparedEdit> edit)
{
    auto* rawEdit = edit.release();
    PyObject* capsule =
        PyCapsule_New(rawEdit, PreparedEditCapsuleName, preparedEditCapsuleDestructor);
    if (!capsule) {
        delete rawEdit;
    }
    return capsule;
}

Py::Dict preparedEditResultToPython(CollaborationPreparedEditResult result)
{
    Py::Dict pythonResult;
    pythonResult["execution_id"] = Py::Long(result.executionId);
    pythonResult["status"] = Py::String(preparedEditExecutionStatusName(result.status));
    pythonResult["diagnostic"] = Py::String(result.diagnostic);
    if (result.preparedEdit) {
        PyObject* capsule = preparedEditToCapsule(std::move(result.preparedEdit));
        if (!capsule) {
            throw Py::Exception();
        }
        pythonResult["prepared_edit"] = Py::Object(capsule, true);
    }
    else {
        pythonResult["prepared_edit"] = Py::None();
    }
    return pythonResult;
}

}  // namespace


PyObject* DocumentPy::addProperty(PyObject* args, PyObject* kwd)
{
    char* sType {nullptr};
    char* sName {nullptr};
    char* sGroup {nullptr};
    char* sDoc {nullptr};
    short attr = 0;
    std::string sDocStr;
    PyObject *ro = Py_False, *hd = Py_False, *lk = Py_False;
    PyObject* enumVals = nullptr;
    static const std::array<const char*, 10> kwlist {"type",
                                                    "name",
                                                    "group",
                                                    "doc",
                                                    "attr",
                                                    "read_only",
                                                    "hidden",
                                                    "locked",
                                                    "enum_vals",
                                                    nullptr};
    if (!Base::Wrapped_ParseTupleAndKeywords(args,
                                             kwd,
                                             "ss|sethO!O!O!O",
                                             kwlist,
                                             &sType,
                                             &sName,
                                             &sGroup,
                                             "utf-8",
                                             &sDoc,
                                             &attr,
                                             &PyBool_Type,
                                             &ro,
                                             &PyBool_Type,
                                             &hd,
                                             &PyBool_Type,
                                             &lk,
                                             &enumVals)) {
        return nullptr;
    }

    if (sDoc) {
        sDocStr = sDoc;
        PyMem_Free(sDoc);
    }

    Property* prop = getDocumentPtr()->addDynamicProperty(sType,
                                                          sName,
                                                          sGroup,
                                                          sDocStr.c_str(),
                                                          attr,
                                                          Base::asBoolean(ro),
                                                          Base::asBoolean(hd));
    prop->setStatus(Property::LockDynamic, Base::asBoolean(lk));

    // enum support
    auto* propEnum = dynamic_cast<App::PropertyEnumeration*>(prop);
    if (propEnum && enumVals) {
        propEnum->setPyObject(enumVals);
    }

    return Py::new_reference_to(this);
}

PyObject* DocumentPy::removeProperty(PyObject* args)
{
    char* sName;
    if (!PyArg_ParseTuple(args, "s", &sName)) {
        return nullptr;
    }

    bool ok = getDocumentPtr()->removeDynamicProperty(sName);
    return Py_BuildValue("O", (ok ? Py_True : Py_False));
}

// returns a string which represent the object e.g. when printed in python
std::string DocumentPy::representation() const
{
    std::stringstream str;
    str << "<Document '" << getDocumentPtr()->getName() << "' (" << getDocumentPtr()->Label.getValue() << ") >";

    return str.str();
}

PyObject* DocumentPy::save(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }

    PY_TRY
    {
        if (!getDocumentPtr()->save()) {
            if (*(getDocumentPtr()->FileName.getValue()) == '\0') {
                PyErr_SetString(PyExc_ValueError, "Object attribute 'FileName' is not set");
            }
            else {
                PyErr_SetString(PyExc_IOError, "Failed to save document");
            }
            return nullptr;
        }
    }
    PY_CATCH;

    const char* filename = getDocumentPtr()->FileName.getValue();
    Base::FileInfo fi(filename);
    if (!fi.isReadable()) {
        PyErr_Format(PyExc_IOError, "No such file or directory: '%s'", filename);
        return nullptr;
    }

    Py_Return;
}

PyObject* DocumentPy::saveWithOutcome(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    PY_TRY
    {
        return Py::new_reference_to(saveOutcomeToPy(getDocumentPtr()->saveWithOutcome()));
    }
    PY_CATCH
}

PyObject* DocumentPy::forceSave(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    PY_TRY
    {
        return Py::new_reference_to(saveOutcomeToPy(getDocumentPtr()->forceSave()));
    }
    PY_CATCH
}

PyObject* DocumentPy::saveAs(PyObject* args)
{
    char* fn;
    if (!PyArg_ParseTuple(args, "et", "utf-8", &fn)) {
        return nullptr;
    }

    std::string utf8Name = fn;
    PyMem_Free(fn);

    PY_TRY
    {
        // Preserve the legacy Python contract: saveAs() returns None when the
        // C++ bool result is false. Callers that need an unambiguous failure
        // result use saveAsWithOutcome().
        static_cast<void>(getDocumentPtr()->saveAs(utf8Name.c_str()));
        Py_Return;
    }
    PY_CATCH
}

PyObject* DocumentPy::saveAsWithPolicy(PyObject* args)
{
    char* fn;
    PyObject* overwriteObject = Py_False;
    if (!PyArg_ParseTuple(args, "et|O!", "utf-8", &fn, &PyBool_Type, &overwriteObject)) {
        return nullptr;
    }

    std::string utf8Name = fn;
    PyMem_Free(fn);

    PY_TRY
    {
        const auto status = getDocumentPtr()->saveAsWithPolicy(
            utf8Name.c_str(), Base::asBoolean(overwriteObject));
        Py::Dict result;
        result["success"] = Py::Boolean(status == DocumentSaveAsStatus::Saved);
        switch (status) {
            case DocumentSaveAsStatus::Saved:
                result["status"] = Py::String("saved");
                break;
            case DocumentSaveAsStatus::DestinationExists:
                result["status"] = Py::String("destination_exists");
                break;
            case DocumentSaveAsStatus::SaveFailed:
                result["status"] = Py::String("save_failed");
                break;
        }
        return Py::new_reference_to(result);
    }
    PY_CATCH
}

PyObject* DocumentPy::saveAsWithOutcome(PyObject* args)
{
    char* fn;
    char* expectedDestinationSha256 = nullptr;
    PyObject* overwriteObject = Py_False;
    if (!PyArg_ParseTuple(args,
                          "et|O!et",
                          "utf-8",
                          &fn,
                          &PyBool_Type,
                          &overwriteObject,
                          "utf-8",
                          &expectedDestinationSha256)) {
        return nullptr;
    }

    std::string utf8Name = fn;
    PyMem_Free(fn);
    std::string expectedHash;
    if (expectedDestinationSha256) {
        expectedHash = expectedDestinationSha256;
        PyMem_Free(expectedDestinationSha256);
    }
    PY_TRY
    {
        return Py::new_reference_to(saveOutcomeToPy(getDocumentPtr()->saveAsWithOutcome(
            utf8Name.c_str(), Base::asBoolean(overwriteObject), expectedHash)));
    }
    PY_CATCH
}

PyObject* DocumentPy::saveCopy(PyObject* args)
{
    char* fn;
    if (!PyArg_ParseTuple(args, "et", "utf-8", &fn)) {
        return nullptr;
    }

    std::string utf8Name = fn;
    PyMem_Free(fn);

    PY_TRY
    {
        static_cast<void>(getDocumentPtr()->saveCopy(utf8Name.c_str()));
        Py_Return;
    }
    PY_CATCH
}

PyObject* DocumentPy::saveCopyWithOutcome(PyObject* args)
{
    char* fn;
    if (!PyArg_ParseTuple(args, "et", "utf-8", &fn)) {
        return nullptr;
    }
    std::string utf8Name = fn;
    PyMem_Free(fn);
    PY_TRY
    {
        return Py::new_reference_to(
            saveOutcomeToPy(getDocumentPtr()->saveCopyWithOutcome(utf8Name.c_str())));
    }
    PY_CATCH
}

PyObject* DocumentPy::hasPendingFileChanges(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    return Py::new_reference_to(Py::Boolean(getDocumentPtr()->hasPendingFileChanges()));
}

PyObject* DocumentPy::getFileChangeState(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    const auto* document = getDocumentPtr();
    Py::Dict result;
    result["state"] = Py::String(fileStateName(document->getFileChangeState()));
    result["canonical_path"] = Py::String(document->FileName.getStrValue());
    result["has_pending_file_changes"] = Py::Boolean(document->hasPendingFileChanges());
    result["last_canonical_save_failed"] = Py::Boolean(
        document->lastCanonicalSaveFailed());
    Py::List pending;
    const auto changes = document->getPendingFileChanges();
    if (changes.testFlag(DocumentFileChange::Model)) {
        pending.append(Py::String("model"));
    }
    if (changes.testFlag(DocumentFileChange::Appearance)) {
        pending.append(Py::String("appearance"));
    }
    result["pending_changes"] = pending;
    return Py::new_reference_to(result);
}

PyObject* DocumentPy::getMutationReadiness(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    const auto readiness = getDocumentPtr()->getMutationReadiness();
    Py::Dict result;
    result["stable_event_supported"] = Py::Boolean(readiness.stableEventSupported);
    result["ready"] = Py::Boolean(readiness.ready);
    result["pending_transaction"] = Py::Boolean(readiness.pendingTransaction);
    result["booked_transaction"] = Py::Long(readiness.bookedTransaction);
    result["transaction_locked"] = Py::Boolean(readiness.transactionLocked);
    result["recomputing"] = Py::Boolean(readiness.recomputing);
    result["must_execute"] = Py::Boolean(readiness.mustExecute);
    result["pending_removal"] = Py::Boolean(readiness.pendingRemoval);
    result["commit_barrier"] = Py::Boolean(readiness.commitBarrier);
    result["notification_replay"] = Py::Boolean(readiness.notificationReplay);
    result["poisoned"] = Py::Boolean(readiness.poisoned);
    result["quarantined"] = Py::Boolean(readiness.quarantined);
    result["diagnostic"] = Py::String(readiness.diagnostic);
    return Py::new_reference_to(result);
}

PyObject* DocumentPy::canWriteRecoverySnapshot(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }

    return Py::new_reference_to(Py::Boolean(getDocumentPtr()->canWriteRecoverySnapshot()));
}

PyObject* DocumentPy::load(PyObject* args)
{
    char* filename = nullptr;
    if (!PyArg_ParseTuple(args, "s", &filename)) {
        return nullptr;
    }
    if (!filename || *filename == '\0') {
        PyErr_Format(PyExc_ValueError, "Path is empty");
        return nullptr;
    }

    getDocumentPtr()->FileName.setValue(filename);
    Base::FileInfo fi(filename);
    if (!fi.isReadable()) {
        PyErr_Format(PyExc_IOError, "No such file or directory: '%s'", filename);
        return nullptr;
    }
    try {
        getDocumentPtr()->restore();
    }
    catch (...) {
        PyErr_Format(PyExc_IOError, "Reading from file '%s' failed", filename);
        return nullptr;
    }
    Py_Return;
}

PyObject* DocumentPy::restore(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    const char* filename = getDocumentPtr()->FileName.getValue();
    if (!filename || *filename == '\0') {
        PyErr_Format(PyExc_ValueError, "Object attribute 'FileName' is not set");
        return nullptr;
    }
    Base::FileInfo fi(filename);
    if (!fi.isReadable()) {
        PyErr_Format(PyExc_IOError, "No such file or directory: '%s'", filename);
        return nullptr;
    }
    try {
        getDocumentPtr()->restore();
    }
    catch (...) {
        PyErr_Format(PyExc_IOError, "Reading from file '%s' failed", filename);
        return nullptr;
    }
    Py_Return;
}

PyObject* DocumentPy::isSaved(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->isSaved();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject* DocumentPy::getProgramVersion(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    const char* version = getDocumentPtr()->getProgramVersion();
    return Py::new_reference_to(Py::String(version));
}

PyObject* DocumentPy::getFileName(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    const char* fn = getDocumentPtr()->getFileName();
    return Py::new_reference_to(Py::String(fn));
}

PyObject* DocumentPy::settings(PyObject* args) const
{
    PyObject* namespaceObject = nullptr;
    if (!PyArg_ParseTuple(args, "O", &namespaceObject)) {
        return nullptr;
    }

    if (!PyUnicode_Check(namespaceObject)) {
        PyErr_SetString(PyExc_TypeError, "namespace must be a string");
        return nullptr;
    }

    const char* namespaceName = PyUnicode_AsUTF8(namespaceObject);
    if (!namespaceName) {
        return nullptr;
    }

    auto* settings = new DocumentSettingsPy(new DocumentSettings(getDocumentPtr(), namespaceName));
    if (isConst()) {
        settings->setConst();
    }

    return Py::new_reference_to(Py::asObject(settings));
}

PyObject* DocumentPy::getUniqueObjectName(PyObject* args)
{
    char* sName;
    if (!PyArg_ParseTuple(args, "s", &sName)) {
        return nullptr;
    }
    PY_TRY
    {
        auto newName = getDocumentPtr()->getUniqueObjectName(sName);
        return Py::new_reference_to(Py::String(newName));
    }
    PY_CATCH;
}

PyObject* DocumentPy::mergeProject(PyObject* args)
{
    char* filename;
    if (!PyArg_ParseTuple(args, "s", &filename)) {
        return nullptr;
    }

    PY_TRY
    {
        Base::FileInfo fi(filename);
        Base::ifstream str(fi, std::ios::in | std::ios::binary);
        App::Document* doc = getDocumentPtr();
        MergeDocuments md(doc);
        md.importObjects(str);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::exportGraphviz(PyObject* args)
{
    char* fn = nullptr;
    if (!PyArg_ParseTuple(args, "|s", &fn)) {
        return nullptr;
    }
    if (fn) {
        Base::FileInfo fi(fn);
        Base::ofstream str(fi);
        getDocumentPtr()->exportGraphviz(str);
        str.close();
        Py_Return;
    }
    else {
        std::stringstream str;
        getDocumentPtr()->exportGraphviz(str);
        return PyUnicode_FromString(str.str().c_str());
    }
}

PyObject* DocumentPy::addObject(PyObject* args, PyObject* kwd)
{
    char *sType, *sName = nullptr, *sViewType = nullptr;
    PyObject* obj = nullptr;
    PyObject* view = nullptr;
    PyObject* attach = Py_False;
    static const std::array<const char*, 7>
        kwlist {"type", "name", "objProxy", "viewProxy", "attach", "viewType", nullptr};
    if (!Base::Wrapped_ParseTupleAndKeywords(args,
                                             kwd,
                                             "s|sOOO!s",
                                             kwlist,
                                             &sType,
                                             &sName,
                                             &obj,
                                             &view,
                                             &PyBool_Type,
                                             &attach,
                                             &sViewType)) {
        return nullptr;
    }

    DocumentObject* pcFtr = nullptr;

    if (!obj || !Base::asBoolean(attach)) {
        pcFtr = getDocumentPtr()->addObject(sType, sName, true, sViewType);
    }
    else {
        Base::Type type =
            Base::Type::getTypeIfDerivedFrom(sType, DocumentObject::getClassTypeId(), true);
        if (type.isBad()) {
            std::stringstream str;
            str << "'" << sType << "' is not a document object type";
            throw Base::TypeError(str.str());
        }
        pcFtr = static_cast<DocumentObject*>(type.createInstance());
    }
    // the type instance could be a null pointer
    if (!pcFtr) {
        std::stringstream str;
        str << "No document object found of type '" << sType << "'" << std::ends;
        throw Py::TypeError(str.str());
    }
    // Allows one to hide the handling with Proxy in client python code
    if (obj) {
        try {
            // the python binding class to the document object
            Py::Object pyftr = Py::asObject(pcFtr->getPyObject());
            // 'pyobj' is the python class with the implementation for DocumentObject
            Py::Object pyobj(obj);
            if (pyobj.hasAttr("__object__")) {
                pyobj.setAttr("__object__", pyftr);
            }
            pyftr.setAttr("Proxy", pyobj);

            if (Base::asBoolean(attach)) {
                getDocumentPtr()->addObject(pcFtr, sName);

                try {
                    Py::Callable method(pyobj.getAttr("attach"));
                    if (!method.isNone()) {
                        Py::TupleN arg(pyftr);
                        method.apply(arg);
                    }
                }
                catch (Py::Exception&) {
                    Base::PyException e;
                    e.reportException();
                }
            }

            // if a document class is set we also need a view provider defined which must be
            // something different to None
            Py::Object pyvp;
            if (view) {
                pyvp = Py::Object(view);
            }
            if (pyvp.isNone()) {
                pyvp = Py::Long(1);
            }
            // 'pyvp' is the python class with the implementation for ViewProvider
            if (pyvp.hasAttr("__vobject__")) {
                pyvp.setAttr("__vobject__", pyftr.getAttr("ViewObject"));
            }

            Py::Object pyprx(pyftr.getAttr("ViewObject"));
            pyprx.setAttr("Proxy", pyvp);
            return Py::new_reference_to(pyftr);
        }
        catch (Py::Exception& e) {
            e.clear();
        }
    }
    return pcFtr->getPyObject();
}

PyObject* DocumentPy::removeObject(PyObject* args)
{
    char* sName {};
    if (PyArg_ParseTuple(args, "s", &sName)) {
        DocumentObject* object = getDocumentPtr()->getObject(sName);
        if (object) {
            getDocumentPtr()->removeObject(sName);
            Py_Return;
        }

        std::stringstream str;
        str << "No document object found with name '" << sName << "'" << std::ends;
        throw Py::ValueError(str.str());
    }

    PyErr_Clear();
    PyObject* objpy {};
    if (PyArg_ParseTuple(args, "O!", &App::DocumentObjectPy::Type, &objpy)) {
        DocumentObject* object = static_cast<App::DocumentObjectPy*>(objpy)->getDocumentObjectPtr();
        if (!object) {
            PyErr_Format(PyExc_RuntimeError, "Invalid document object");
            return nullptr;
        }

        if (object->getDocument() == getDocumentPtr()) {
            getDocumentPtr()->removeObject(object);
            Py_Return;
        }

        std::stringstream str;
        str << "Document object is not part of this document";
        throw Py::ValueError(str.str());
    }

    PyErr_SetString(PyExc_TypeError, "Expect str or DocumentObject");
    return nullptr;
}

PyObject* DocumentPy::copyObject(PyObject* args, PyObject* kwd)
{
    PyObject* obj;
    PyObject* rec = Py_False;
    PyObject* retAll = Py_False;
    static constexpr std::array<const char*, 4> kwlist {"object", "recursive", "return_all", nullptr};
    if (!Base::Wrapped_ParseTupleAndKeywords(args,
                                             kwd,
                                             "O|O!O!",
                                             kwlist,
                                             &obj,
                                             &PyBool_Type,
                                             &rec,
                                             &PyBool_Type,
                                             &retAll)) {
        return nullptr;
    }

    std::vector<App::DocumentObject*> objs;
    bool single = false;
    if (PySequence_Check(obj)) {
        Py::Sequence seq(obj);
        for (Py_ssize_t i = 0; i < seq.size(); ++i) {
            if (!PyObject_TypeCheck(seq[i].ptr(), &DocumentObjectPy::Type)) {
                PyErr_SetString(PyExc_TypeError,
                                "Expect element in sequence to be of type document object");
                return nullptr;
            }
            objs.push_back(static_cast<DocumentObjectPy*>(seq[i].ptr())->getDocumentObjectPtr());
        }
    }
    else if (!PyObject_TypeCheck(obj, &DocumentObjectPy::Type)) {
        PyErr_SetString(
            PyExc_TypeError,
            "Expect first argument to be either a document object or sequence of document objects");
        return nullptr;
    }
    else {
        objs.push_back(static_cast<DocumentObjectPy*>(obj)->getDocumentObjectPtr());
        single = true;
    }

    PY_TRY
    {
        auto ret =
            getDocumentPtr()->copyObject(objs, Base::asBoolean(rec), Base::asBoolean(retAll));
        if (ret.size() == 1 && single) {
            return ret[0]->getPyObject();
        }

        Py::Tuple tuple(ret.size());
        for (size_t i = 0; i < ret.size(); ++i) {
            tuple.setItem(i, Py::Object(ret[i]->getPyObject(), true));
        }
        return Py::new_reference_to(tuple);
    }
    PY_CATCH
}

PyObject* DocumentPy::importLinks(PyObject* args)
{
    PyObject* obj = Py_None;
    if (!PyArg_ParseTuple(args, "|O", &obj)) {
        return nullptr;
    }

    std::vector<App::DocumentObject*> objs;
    if (PySequence_Check(obj)) {
        Py::Sequence seq(obj);
        for (Py_ssize_t i = 0; i < seq.size(); ++i) {
            if (!PyObject_TypeCheck(seq[i].ptr(), &DocumentObjectPy::Type)) {
                PyErr_SetString(PyExc_TypeError,
                                "Expect element in sequence to be of type document object");
                return nullptr;
            }
            objs.push_back(static_cast<DocumentObjectPy*>(seq[i].ptr())->getDocumentObjectPtr());
        }
    }
    else {
        Base::PyTypeCheck(&obj,
                          &DocumentObjectPy::Type,
                          "Expect first argument to be either a document object, sequence of "
                          "document objects or None");
        if (obj) {
            objs.push_back(static_cast<DocumentObjectPy*>(obj)->getDocumentObjectPtr());
        }
    }

    if (objs.empty()) {
        objs = getDocumentPtr()->getObjects();
    }

    PY_TRY
    {
        auto ret = getDocumentPtr()->importLinks(objs);

        Py::Tuple tuple(ret.size());
        for (size_t i = 0; i < ret.size(); ++i) {
            tuple.setItem(i, Py::Object(ret[i]->getPyObject(), true));
        }
        return Py::new_reference_to(tuple);
    }
    PY_CATCH
}

PyObject* DocumentPy::moveObject(PyObject* args)
{
    PyObject *obj, *rec = Py_False;
    if (!PyArg_ParseTuple(args, "O!|O!", &(DocumentObjectPy::Type), &obj, &PyBool_Type, &rec)) {
        return nullptr;
    }

    DocumentObjectPy* docObj = static_cast<DocumentObjectPy*>(obj);
    DocumentObject* move =
        getDocumentPtr()->moveObject(docObj->getDocumentObjectPtr(), Base::asBoolean(rec));
    if (move) {
        return move->getPyObject();
    }
    else {
        std::string str("Failed to move the object");
        throw Py::ValueError(str);
    }
}

PyObject* DocumentPy::openTransaction(PyObject* args)
{
    PyObject* value = nullptr;
    if (!PyArg_ParseTuple(args, "|O", &value)) {
        return nullptr;
    }
    std::string cmd;


    if (!value) {
        cmd = "<empty>";
    }
    else if (PyUnicode_Check(value)) {
        cmd = PyUnicode_AsUTF8(value);
    }
    else {
        PyErr_SetString(PyExc_TypeError, "string or unicode expected");
        return nullptr;
    }

    getDocumentPtr()->openTransaction(cmd.c_str());
    Py_Return;
}

PyObject* DocumentPy::abortTransaction(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->abortTransaction();
    Py_Return;
}

PyObject* DocumentPy::commitTransaction(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->commitTransaction();
    Py_Return;
}

PyObject* DocumentPy::collaborationIdentity(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    PY_TRY
    {
        const auto identity = getDocumentPtr()->collaborationIdentity();
        Py::Dict result;
        result["instance_id"] = Py::Long(identity.instanceId);
        result["lifecycle_epoch"] = Py::Long(identity.lifecycleEpoch);
        result["state"] = Py::String(documentLifecycleStateName(identity.state));
        return Py::new_reference_to(result);
    }
    PY_CATCH;
}

PyObject* DocumentPy::captureSemanticRevisions(PyObject* args)
{
    PyObject* revisionKeys = nullptr;
    if (!PyArg_ParseTuple(args, "O", &revisionKeys)) {
        return nullptr;
    }
    PY_TRY
    {
        const auto snapshot =
            getDocumentPtr()->collaborationService().captureSemanticRevisions(
                revisionKeysFromPython(revisionKeys));
        Py::Dict result;
        result["document_instance_id"] = Py::Long(snapshot.documentInstanceId);
        result["lifecycle_epoch"] = Py::Long(snapshot.lifecycleEpoch);
        Py::List revisions;
        for (const auto& observation : snapshot.revisions) {
            revisions.append(revisionObservationToPython(observation));
        }
        result["revisions"] = revisions;
        return Py::new_reference_to(result);
    }
    PY_CATCH;
}

PyObject* DocumentPy::beginEditSession(PyObject* args)
{
    const char* actorId = nullptr;
    if (!PyArg_ParseTuple(args, "s", &actorId)) {
        return nullptr;
    }
    PY_TRY
    {
        const auto session =
            getDocumentPtr()->collaborationService().beginEditSession(actorId);
        return Py::new_reference_to(editSessionToPython(session));
    }
    PY_CATCH;
}

PyObject* DocumentPy::snapshotForEdit(PyObject* args)
{
    const char* sessionId = nullptr;
    PyObject* revisionKeys = nullptr;
    if (!PyArg_ParseTuple(args, "sO", &sessionId, &revisionKeys)) {
        return nullptr;
    }
    PY_TRY
    {
        const auto snapshot = getDocumentPtr()->collaborationService().snapshotForEdit(
            sessionId,
            revisionKeysFromPython(revisionKeys));
        Py::Dict result;
        result["session_id"] = Py::String(snapshot.sessionId);
        result["document_instance_id"] = Py::Long(snapshot.documentInstanceId);
        result["lifecycle_epoch"] = Py::Long(snapshot.lifecycleEpoch);
        Py::List revisions;
        for (const auto& observation : snapshot.revisions) {
            revisions.append(revisionObservationToPython(observation));
        }
        result["revisions"] = revisions;
        return Py::new_reference_to(result);
    }
    PY_CATCH;
}

PyObject* DocumentPy::prepareEdit(PyObject* args)
{
    const char* sessionId = nullptr;
    const char* operationId = nullptr;
    const char* operationType = nullptr;
    PyObject* arguments = nullptr;
    const char* provenance = "python";
    if (!PyArg_ParseTuple(args,
                          "sssO|s",
                          &sessionId,
                          &operationId,
                          &operationType,
                          &arguments,
                          &provenance)) {
        return nullptr;
    }
    PY_TRY
    {
        CollaborativeOperationIntent intent;
        intent.operationType = operationType;
        intent.arguments = stringMapFromPython(arguments);
        auto prepared = getDocumentPtr()->collaborationService().prepareEdit(sessionId,
                                                                             operationId,
                                                                             intent,
                                                                             provenance);
        return preparedEditToCapsule(std::make_unique<PreparedEdit>(std::move(prepared)));
    }
    PY_CATCH;
}

PyObject* DocumentPy::prepareEditWithExpectedRevisions(PyObject* args)
{
    const char* sessionId = nullptr;
    const char* operationId = nullptr;
    const char* operationType = nullptr;
    PyObject* arguments = nullptr;
    PyObject* expectedRevisions = nullptr;
    const char* provenance = "python";
    if (!PyArg_ParseTuple(args,
                          "sssOO|s",
                          &sessionId,
                          &operationId,
                          &operationType,
                          &arguments,
                          &expectedRevisions,
                          &provenance)) {
        return nullptr;
    }
    PY_TRY
    {
        CollaborativeOperationIntent intent;
        intent.operationType = operationType;
        intent.arguments = stringMapFromPython(arguments);
        auto prepared =
            getDocumentPtr()->collaborationService().prepareEditWithExpectedRevisions(
                sessionId,
                operationId,
                intent,
                revisionObservationsFromPython(expectedRevisions),
                provenance);
        return preparedEditToCapsule(std::make_unique<PreparedEdit>(std::move(prepared)));
    }
    PY_CATCH;
}

PyObject* DocumentPy::prepareEditAsync(PyObject* args)
{
    const char* sessionId = nullptr;
    const char* operationId = nullptr;
    const char* operationType = nullptr;
    PyObject* arguments = nullptr;
    const char* provenance = "python";
    if (!PyArg_ParseTuple(args,
                          "sssO|s",
                          &sessionId,
                          &operationId,
                          &operationType,
                          &arguments,
                          &provenance)) {
        return nullptr;
    }
    PY_TRY
    {
        CollaborativeOperationIntent intent;
        intent.operationType = operationType;
        intent.arguments = stringMapFromPython(arguments);
        const auto executionId = getDocumentPtr()->collaborationService().prepareEditAsync(
            sessionId, operationId, intent, provenance);
        return Py::new_reference_to(Py::Long(executionId));
    }
    PY_CATCH;
}

PyObject* DocumentPy::preparedEditStatus(PyObject* args)
{
    unsigned long long executionId = 0;
    if (!PyArg_ParseTuple(args, "K", &executionId)) {
        return nullptr;
    }
    PY_TRY
    {
        const auto status = getDocumentPtr()->collaborationService().preparedEditStatus(
            static_cast<PreparedEditExecutionId>(executionId));
        if (!status) {
            Py_RETURN_NONE;
        }
        return Py::new_reference_to(preparedEditExecutionSnapshotToPython(*status));
    }
    PY_CATCH;
}

PyObject* DocumentPy::cancelPreparedEdit(PyObject* args)
{
    unsigned long long executionId = 0;
    if (!PyArg_ParseTuple(args, "K", &executionId)) {
        return nullptr;
    }
    PY_TRY
    {
        return Py::new_reference_to(Py::Boolean(
            getDocumentPtr()->collaborationService().cancelPreparedEdit(
                static_cast<PreparedEditExecutionId>(executionId))));
    }
    PY_CATCH;
}

PyObject* DocumentPy::takePreparedEdit(PyObject* args)
{
    const char* sessionId = nullptr;
    unsigned long long executionId = 0;
    if (!PyArg_ParseTuple(args, "sK", &sessionId, &executionId)) {
        return nullptr;
    }
    PY_TRY
    {
        auto result = getDocumentPtr()->collaborationService().takePreparedEdit(
            sessionId, static_cast<PreparedEditExecutionId>(executionId));
        if (!result) {
            Py_RETURN_NONE;
        }
        return Py::new_reference_to(preparedEditResultToPython(std::move(*result)));
    }
    PY_CATCH;
}

PyObject* DocumentPy::commitEdit(PyObject* args)
{
    const char* sessionId = nullptr;
    PyObject* prepared = nullptr;
    if (!PyArg_ParseTuple(args, "sO", &sessionId, &prepared)) {
        return nullptr;
    }
    PY_TRY
    {
        const auto result = getDocumentPtr()->collaborationService().commitEdit(
            sessionId,
            preparedEditFromCapsule(prepared));
        return Py::new_reference_to(commitResultToPython(result));
    }
    PY_CATCH;
}

PyObject* DocumentPy::commitCompatibilityMutation(PyObject* args, PyObject* kwd)
{
    PyObject* callback = nullptr;
    PyObject* structural = Py_False;
    PyObject* recompute = Py_True;
    PyObject* postcondition = Py_None;
    const char* objectName = nullptr;
    static const std::array<const char*, 6> kwlist {"",
                                                    "structural",
                                                    "recompute",
                                                    "postcondition",
                                                    "object_name",
                                                    nullptr};
    if (!Base::Wrapped_ParseTupleAndKeywords(args,
                                             kwd,
                                             "O|$O!O!Oz:commitCompatibilityMutation",
                                             kwlist,
                                             &callback,
                                             &PyBool_Type,
                                             &structural,
                                             &PyBool_Type,
                                             &recompute,
                                             &postcondition,
                                             &objectName)) {
        return nullptr;
    }
    if (!PyCallable_Check(callback)) {
        PyErr_SetString(PyExc_TypeError, "callback must be callable");
        return nullptr;
    }
    if (postcondition != Py_None && !PyCallable_Check(postcondition)) {
        PyErr_SetString(PyExc_TypeError, "postcondition must be callable or None");
        return nullptr;
    }

    PY_TRY
    {
        const auto retainCallable = [](PyObject* callable) {
            Py_INCREF(callable);
            return std::shared_ptr<PyObject>(callable, [](PyObject* object) {
                if (!object || !Py_IsInitialized()) {
                    return;
                }
                Base::PyGILStateLocker gil;
                Py_DECREF(object);
            });
        };
        auto retainedCallback = retainCallable(callback);
        std::shared_ptr<PyObject> retainedPostcondition;
        if (postcondition != Py_None) {
            retainedPostcondition = retainCallable(postcondition);
        }
        auto callbackError = std::make_shared<PythonCompatibilityCallbackError>();
        try {
            CollaborationCompatibilityMutation mutation;
            const bool structuralScope = Base::asBoolean(structural);
            if (objectName != nullptr && *objectName != '\0') {
                if (structuralScope) {
                    throw Base::ValueError(
                        "commitCompatibilityMutation cannot combine structural=True with object_name");
                }
                const auto* object = getDocumentPtr()->getObject(objectName);
                if (!object) {
                    throw Base::ValueError(
                        "commitCompatibilityMutation object_name does not name a live document object");
                }
                mutation.scope = CollaborationCompatibilityScope::ObjectModel;
                mutation.objectName = objectName;
                mutation.stableObjectIdentity =
                    getDocumentPtr()->collaborationObjectIdentity(*object);
            }
            else if (structuralScope) {
                mutation.scope = CollaborationCompatibilityScope::Structural;
            }
            else {
                mutation.scope = CollaborationCompatibilityScope::UnknownModel;
            }
            CollaborationCompatibilityCallback nativeCallback =
                [retainedCallback = std::move(retainedCallback), callbackError] {
                    Base::PyGILStateLocker gil;
                    PyObject* callbackResult = PyObject_CallNoArgs(retainedCallback.get());
                    if (!callbackResult) {
                        callbackError->capture();
                        throw PythonCompatibilityCallbackFailure();
                    }
                    Py_DECREF(callbackResult);
                };
            CollaborationCompatibilityPostcondition nativePostcondition;
            if (retainedPostcondition) {
                nativePostcondition =
                    [retainedPostcondition = std::move(retainedPostcondition), callbackError] {
                        Base::PyGILStateLocker gil;
                        PyObject* postconditionResult =
                            PyObject_CallNoArgs(retainedPostcondition.get());
                        if (!postconditionResult) {
                            callbackError->capture();
                            throw PythonCompatibilityCallbackFailure();
                        }
                        const int satisfied = PyObject_IsTrue(postconditionResult);
                        if (satisfied < 0) {
                            callbackError->capture();
                            Py_DECREF(postconditionResult);
                            throw PythonCompatibilityCallbackFailure();
                        }
                        Py_DECREF(postconditionResult);
                        return satisfied != 0;
                    };
            }
            CollaborationCompatibilityMutationOptions options;
            options.recomputePolicy = Base::asBoolean(recompute)
                ? CollaborationCompatibilityRecomputePolicy::Eager
                : CollaborationCompatibilityRecomputePolicy::Deferred;
            options.postcondition = std::move(nativePostcondition);
            const auto result = getDocumentPtr()
                                    ->collaborationService()
                                    .commitCompatibilityMutationWithOptions(
                                        std::move(mutation),
                                        std::move(nativeCallback),
                                        std::move(options));
            return Py::new_reference_to(commitResultToPython(result));
        }
        catch (const PythonCompatibilityCallbackFailure&) {
            callbackError->restore();
            return nullptr;
        }
        catch (...) {
            if (callbackError->captured()) {
                callbackError->restore();
                return nullptr;
            }
            throw;
        }
    }
    PY_CATCH;
}

PyObject* DocumentPy::cancelEdit(PyObject* args)
{
    const char* sessionId = nullptr;
    const char* reason = "cancelled by caller";
    if (!PyArg_ParseTuple(args, "s|s", &sessionId, &reason)) {
        return nullptr;
    }
    PY_TRY
    {
        return Py::new_reference_to(Py::Boolean(
            getDocumentPtr()->collaborationService().cancelEdit(sessionId, reason)));
    }
    PY_CATCH;
}

PyObject* DocumentPy::editSessionStatus(PyObject* args)
{
    const char* sessionId = nullptr;
    if (!PyArg_ParseTuple(args, "s", &sessionId)) {
        return nullptr;
    }
    PY_TRY
    {
        const auto status =
            getDocumentPtr()->collaborationService().sessionStatus(sessionId);
        if (!status) {
            Py_RETURN_NONE;
        }
        return Py::new_reference_to(editSessionToPython(*status));
    }
    PY_CATCH;
}

Py::Boolean DocumentPy::getHasPendingTransaction() const
{
    return {getDocumentPtr()->hasPendingTransaction()};
}

PyObject* DocumentPy::undo(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    if (getDocumentPtr()->getAvailableUndos()) {
        getDocumentPtr()->undo();
    }
    Py_Return;
}

PyObject* DocumentPy::redo(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    if (getDocumentPtr()->getAvailableRedos()) {
        getDocumentPtr()->redo();
    }
    Py_Return;
}

PyObject* DocumentPy::clearUndos(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->clearUndos();
    Py_Return;
}

PyObject* DocumentPy::clearDocument(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->clearDocument();
    Py_Return;
}

PyObject* DocumentPy::setClosable(PyObject* args)
{
    PyObject* close;
    if (!PyArg_ParseTuple(args, "O!", &PyBool_Type, &close)) {
        return nullptr;
    }
    getDocumentPtr()->setClosable(Base::asBoolean(close));
    Py_Return;
}

PyObject* DocumentPy::isClosable(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->isClosable();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject *DocumentPy::setAutoCreated(PyObject *args)
{
    PyObject *autoCreated;
    if (!PyArg_ParseTuple(args, "O!", &PyBool_Type, &autoCreated)) {
        return nullptr;
    }
    bool value = (autoCreated == Py_True);
    getDocumentPtr()->setAutoCreated(value);

    Py_RETURN_NONE;
}

PyObject *DocumentPy::isAutoCreated(PyObject *args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->isAutoCreated();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject* DocumentPy::recompute(PyObject* args)
{
    PyObject* pyobjs = Py_None;
    PyObject* force = Py_False;
    PyObject* checkCycle = Py_False;
    if (!PyArg_ParseTuple(args,
                          "|OO!O!",
                          &pyobjs,
                          &PyBool_Type,
                          &force,
                          &PyBool_Type,
                          &checkCycle)) {
        return nullptr;
    }

    PY_TRY
    {
        std::vector<App::DocumentObject*> objs;
        if (pyobjs != Py_None) {
            if (!PySequence_Check(pyobjs)) {
                PyErr_SetString(PyExc_TypeError, "expect input of sequence of document objects");
                return nullptr;
            }

            Py::Sequence seq(pyobjs);
            for (Py_ssize_t i = 0; i < seq.size(); ++i) {
                if (!PyObject_TypeCheck(seq[i].ptr(), &DocumentObjectPy::Type)) {
                    PyErr_SetString(PyExc_TypeError,
                                    "Expect element in sequence to be of type document object");
                    return nullptr;
                }
                objs.push_back(
                    static_cast<DocumentObjectPy*>(seq[i].ptr())->getDocumentObjectPtr());
            }
        }

        int options = 0;
        if (Base::asBoolean(checkCycle)) {
            options = Document::DepNoCycle;
        }

        int objectCount =
            getDocumentPtr()->recompute(objs, Base::asBoolean(force), nullptr, options);

        // Document::recompute() hides possibly raised Python exceptions by its features
        // So, check if an error is set and return null if yes
        if (PyErr_Occurred()) {
            return nullptr;
        }

        return Py::new_reference_to(Py::Long(objectCount));
    }
    PY_CATCH;
}

PyObject* DocumentPy::recomputeAsync(PyObject* args)
{
    PyObject* pyobjs = Py_None;
    PyObject* force = Py_False;
    PyObject* checkCycle = Py_False;
    if (!PyArg_ParseTuple(args,
                          "|OO!O!",
                          &pyobjs,
                          &PyBool_Type,
                          &force,
                          &PyBool_Type,
                          &checkCycle)) {
        return nullptr;
    }

    PY_TRY
    {
        std::vector<App::DocumentObject*> objs;
        if (pyobjs != Py_None) {
            if (!PySequence_Check(pyobjs)) {
                PyErr_SetString(PyExc_TypeError, "expect input of sequence of document objects");
                return nullptr;
            }

            Py::Sequence seq(pyobjs);
            for (Py_ssize_t i = 0; i < seq.size(); ++i) {
                if (!PyObject_TypeCheck(seq[i].ptr(), &DocumentObjectPy::Type)) {
                    PyErr_SetString(PyExc_TypeError,
                                    "Expect element in sequence to be of type document object");
                    return nullptr;
                }
                objs.push_back(
                    static_cast<DocumentObjectPy*>(seq[i].ptr())->getDocumentObjectPtr());
            }
        }

        int options = 0;
        if (Base::asBoolean(checkCycle)) {
            options = Document::DepNoCycle;
        }
        auto handle = getDocumentPtr()->recomputeAsync(
            objs, Base::asBoolean(force), options);
        return new RecomputeHandlePy(handle.release());
    }
    PY_CATCH;
}

PyObject* DocumentPy::mustExecute(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->mustExecute();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject* DocumentPy::isTouched(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->isTouched();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject* DocumentPy::purgeTouched(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->purgeTouched();
    Py_Return;
}

PyObject* DocumentPy::getObject(PyObject* args)
{
    DocumentObject* obj = nullptr;

    do {
        char* name = nullptr;
        if (PyArg_ParseTuple(args, "s", &name)) {
            obj = getDocumentPtr()->getObject(name);
            break;
        }

        PyErr_Clear();
        long id = -1;
        if (PyArg_ParseTuple(args, "l", &id)) {
            obj = getDocumentPtr()->getObjectByID(id);
            break;
        }

        PyErr_SetString(PyExc_TypeError, "a string or integer is required");
        return nullptr;
    } while (false);

    if (obj) {
        return obj->getPyObject();
    }

    Py_Return;
}

PyObject* DocumentPy::getObjectsByLabel(PyObject* args)
{
    char* sName;
    if (!PyArg_ParseTuple(args, "s", &sName)) {
        return nullptr;
    }

    Py::List list;
    std::string name = sName;
    std::vector<DocumentObject*> objs = getDocumentPtr()->getObjects();
    for (auto obj : objs) {
        if (name == obj->Label.getValue()) {
            list.append(Py::asObject(obj->getPyObject()));
        }
    }

    return Py::new_reference_to(list);
}

PyObject* DocumentPy::findObjects(PyObject* args, PyObject* kwds)
{
    const char *sType = "App::DocumentObject", *sName = nullptr, *sLabel = nullptr;
    static const std::array<const char*, 4> kwlist {"Type", "Name", "Label", nullptr};
    if (!Base::Wrapped_ParseTupleAndKeywords(args, kwds, "|sss", kwlist, &sType, &sName, &sLabel)) {
        return nullptr;
    }

    Base::Type type =
        Base::Type::getTypeIfDerivedFrom(sType, App::DocumentObject::getClassTypeId(), true);
    if (type.isBad()) {
        std::stringstream str;
        str << "'" << sType << "' is not a document object type";
        throw Base::TypeError(str.str());
    }

    std::vector<DocumentObject*> res;

    try {
        res = getDocumentPtr()->findObjects(type, sName, sLabel);
    }
    catch (const boost::regex_error& e) {
        PyErr_SetString(PyExc_RuntimeError, e.what());
        return nullptr;
    }

    Py_ssize_t index = 0;
    PyObject* list = PyList_New((Py_ssize_t)res.size());
    for (std::vector<DocumentObject*>::const_iterator It = res.begin(); It != res.end();
         ++It, index++) {
        PyList_SetItem(list, index, (*It)->getPyObject());
    }
    return list;
}

Py::Object DocumentPy::getActiveObject() const
{
    DocumentObject* pcFtr = getDocumentPtr()->getActiveObject();
    if (pcFtr) {
        return Py::Object(pcFtr->getPyObject(), true);
    }
    return Py::None();
}

PyObject* DocumentPy::supportedTypes(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }

    std::vector<Base::Type> ary;
    Base::Type::getAllDerivedFrom(App::DocumentObject::getClassTypeId(), ary);
    Py::List res;
    for (const auto& it : ary) {
        res.append(Base::toPyString(it.getName()));
    }
    return Py::new_reference_to(res);
}

Py::List DocumentPy::getObjects() const
{
    std::vector<DocumentObject*> objs = getDocumentPtr()->getObjects();
    Py::List res;

    for (auto obj : objs) {
        // Note: Here we must force the Py::Object to own this Python object as getPyObject()
        // increments the counter
        res.append(Py::Object(obj->getPyObject(), true));
    }

    return res;
}

Py::List DocumentPy::getTopologicalSortedObjects() const
{
    std::vector<DocumentObject*> objs = getDocumentPtr()->topologicalSort();
    Py::List res;

    for (auto obj : objs) {
        // Note: Here we must force the Py::Object to own this Python object as getPyObject()
        // increments the counter
        res.append(Py::Object(obj->getPyObject(), true));
    }

    return res;
}

Py::List DocumentPy::getRootObjects() const
{
    std::vector<DocumentObject*> objs = getDocumentPtr()->getRootObjects();
    Py::List res;

    for (auto obj : objs) {
        // Note: Here we must force the Py::Object to own this Python object as getPyObject()
        // increments the counter
        res.append(Py::Object(obj->getPyObject(), true));
    }

    return res;
}

Py::List DocumentPy::getRootObjectsIgnoreLinks() const
{
    std::vector<App::DocumentObject*> objs = getDocumentPtr()->getRootObjectsIgnoreLinks();
    Py::List res;

    for (auto obj : objs) {
        // Note: Here we must force the Py::Object to own this Python object as getPyObject()
        // increments the counter
        res.append(Py::Object(obj->getPyObject(), true));
    }

    return res;
}

Py::Long DocumentPy::getUndoMode() const
{
    return Py::Long(1);
}

void DocumentPy::setUndoMode(Py::Long /*arg*/)
{}


Py::Long DocumentPy::getUndoRedoMemSize() const
{
    return Py::Long((long)getDocumentPtr()->getUndoMemSize());
}

Py::Long DocumentPy::getUndoCount() const
{
    return Py::Long((long)getDocumentPtr()->getAvailableUndos());
}

Py::Long DocumentPy::getRedoCount() const
{
    return Py::Long((long)getDocumentPtr()->getAvailableRedos());
}

Py::List DocumentPy::getUndoNames() const
{
    std::vector<std::string> vList = getDocumentPtr()->getAvailableUndoNames();
    Py::List res;

    for (const auto& It : vList) {
        res.append(Py::String(It));
    }

    return res;
}

Py::List DocumentPy::getRedoNames() const
{
    std::vector<std::string> vList = getDocumentPtr()->getAvailableRedoNames();
    Py::List res;

    for (const auto& It : vList) {
        res.append(Py::String(It));
    }

    return res;
}

Py::String DocumentPy::getDependencyGraph() const
{
    std::stringstream out;
    getDocumentPtr()->exportGraphviz(out);
    return {out.str()};
}

Py::String DocumentPy::getName() const
{
    return {getDocumentPtr()->getName()};
}

Py::Boolean DocumentPy::getRecomputesFrozen() const
{
    return {getDocumentPtr()->testStatus(Document::Status::SkipRecompute)};
}

void DocumentPy::setRecomputesFrozen(Py::Boolean arg)
{
    getDocumentPtr()->setStatus(Document::Status::SkipRecompute, arg.isTrue());
}

PyObject* DocumentPy::getTempFileName(PyObject* args)
{
    PyObject* value;
    if (!PyArg_ParseTuple(args, "O", &value)) {
        return nullptr;
    }

    std::string string;
    if (PyUnicode_Check(value)) {
        string = PyUnicode_AsUTF8(value);
    }
    else {
        std::string error = std::string("type must be a string!");
        error += value->ob_type->tp_name;
        throw Py::TypeError(error);
    }

    // search for a temp file name in the document transient directory
    Base::FileInfo fileName(
        Base::FileInfo::getTempFileName(string.c_str(), getDocumentPtr()->TransientDir.getValue()));
    // delete the created file, we need only the name...
    fileName.deleteFile();

    PyObject* p =
        PyUnicode_DecodeUTF8(fileName.filePath().c_str(), fileName.filePath().size(), nullptr);
    if (!p) {
        throw Base::UnicodeError("UTF8 conversion failure at PropertyString::getPyObject()");
    }
    return p;
}

PyObject* DocumentPy::getCustomAttributes(const char* attr) const
{
    // Note: Here we want to return only a document object if its
    // name matches 'attr'. However, it is possible to have an object
    // with the same name as an attribute. If so, we return 0 as other-
    // wise it wouldn't be possible to address this attribute any more.
    // The object must then be addressed by the getObject() method directly.
    App::Property* prop = getPropertyContainerPtr()->getPropertyByName(attr);
    if (prop) {
        return nullptr;
    }
    if (!this->ob_type->tp_dict) {
        if (PyType_Ready(this->ob_type) < 0) {
            return nullptr;
        }
    }
    PyObject* item = PyDict_GetItemString(this->ob_type->tp_dict, attr);
    if (item) {
        return nullptr;
    }
    // search for an object with this name
    DocumentObject* obj = getDocumentPtr()->getObject(attr);
    return (obj ? obj->getPyObject() : nullptr);
}

int DocumentPy::setCustomAttributes(const char* attr, PyObject*)
{
    // Note: Here we want to return only a document object if its
    // name matches 'attr'. However, it is possible to have an object
    // with the same name as an attribute. If so, we return 0 as other-
    // wise it wouldn't be possible to address this attribute any more.
    // The object must then be addressed by the getObject() method directly.
    App::Property* prop = getPropertyContainerPtr()->getPropertyByName(attr);
    if (prop) {
        return 0;
    }
    if (!this->ob_type->tp_dict) {
        if (PyType_Ready(this->ob_type) < 0) {
            return 0;
        }
    }
    PyObject* item = PyDict_GetItemString(this->ob_type->tp_dict, attr);
    if (item) {
        return 0;
    }
    DocumentObject* obj = getDocumentPtr()->getObject(attr);
    if (obj) {
        std::stringstream str;
        str << "'Document' object attribute '" << attr << "' must not be set this way" << std::ends;
        PyErr_SetString(PyExc_RuntimeError, str.str().c_str());
        return -1;
    }

    return 0;
}

PyObject* DocumentPy::getLinksTo(PyObject* args)
{
    PyObject* pyobj = Py_None;
    int options = 0;
    short count = 0;
    if (!PyArg_ParseTuple(args, "|Oih", &pyobj, &options, &count)) {
        return nullptr;
    }

    PY_TRY
    {
        Base::PyTypeCheck(&pyobj,
                          &DocumentObjectPy::Type,
                          "Expect the first argument of type document object");
        DocumentObject* obj = nullptr;
        if (pyobj) {
            obj = static_cast<DocumentObjectPy*>(pyobj)->getDocumentObjectPtr();
        }

        std::set<DocumentObject*> links;
        getDocumentPtr()->getLinksTo(links, obj, options, count);
        Py::Tuple ret(links.size());
        int i = 0;
        for (auto o : links) {
            ret.setItem(i++, Py::Object(o->getPyObject(), true));
        }

        return Py::new_reference_to(ret);
    }
    PY_CATCH
}

Py::List DocumentPy::getInList() const
{
    Py::List ret;
    auto lists = PropertyXLink::getDocumentInList(getDocumentPtr());
    if (lists.size() == 1) {
        for (auto doc : lists.begin()->second) {
            ret.append(Py::Object(doc->getPyObject(), true));
        }
    }
    return ret;
}

Py::List DocumentPy::getOutList() const
{
    Py::List ret;
    auto lists = PropertyXLink::getDocumentOutList(getDocumentPtr());
    if (lists.size() == 1) {
        for (auto doc : lists.begin()->second) {
            ret.append(Py::Object(doc->getPyObject(), true));
        }
    }
    return ret;
}

PyObject* DocumentPy::getDependentDocuments(PyObject* args)
{
    PyObject* sort = Py_True;
    if (!PyArg_ParseTuple(args, "|O!", &PyBool_Type, &sort)) {
        return nullptr;
    }
    PY_TRY
    {
        auto docs = getDocumentPtr()->getDependentDocuments(Base::asBoolean(sort));
        Py::List ret;
        for (auto doc : docs) {
            ret.append(Py::Object(doc->getPyObject(), true));
        }
        return Py::new_reference_to(ret);
    }
    PY_CATCH;
}
PyObject* DocumentPy::getBookedTransactionID(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    int tid = getDocumentPtr()->getBookedTransactionID();
    return Py::new_reference_to(Py::Long(tid));
}

Py::Boolean DocumentPy::getRestoring() const
{
    return {getDocumentPtr()->testStatus(Document::Status::Restoring)};
}

Py::Boolean DocumentPy::getPartial() const
{
    return {getDocumentPtr()->testStatus(Document::Status::PartialDoc)};
}

Py::Boolean DocumentPy::getImporting() const
{
    return {getDocumentPtr()->testStatus(Document::Status::Importing)};
}

Py::Boolean DocumentPy::getRecomputing() const
{
    return {getDocumentPtr()->testStatus(Document::Status::Recomputing)};
}

Py::Boolean DocumentPy::getTransacting() const
{
    return {getDocumentPtr()->isPerformingTransaction()};
}

Py::String DocumentPy::getOldLabel() const
{
    return {getDocumentPtr()->getOldLabel()};
}

Py::Boolean DocumentPy::getTemporary() const
{
    return {getDocumentPtr()->testStatus(Document::TempDoc)};
}
